# Generated by Django 3.1.2 on 2020-11-06 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ADMIT_PATIENT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PATIENT_ID', models.CharField(max_length=45)),
                ('PATIENT_NAME', models.CharField(max_length=45)),
                ('PATIENT_FHR_HUS_NAME', models.CharField(max_length=45)),
                ('PATIENT_AGE', models.IntegerField()),
                ('PATIENT_ADMIT_DATE_TIME', models.DateTimeField()),
                ('PATIENT_DISCHARGE_DATE_TIME', models.DateTimeField(null=True)),
                ('PATIENT_BIRTH_DATE', models.DateField()),
                ('PATIENT_SEX', models.CharField(max_length=7)),
                ('PATIENT_STREET1', models.CharField(max_length=100)),
                ('PATIENT_STREET2', models.CharField(max_length=100)),
                ('PATIENT_DISTRICT', models.CharField(max_length=45)),
                ('PATIENT_CITY', models.CharField(max_length=45)),
                ('PATIENT_STATE', models.CharField(max_length=45)),
                ('PATIENT_PINCODE', models.CharField(max_length=45)),
                ('PATIENT_MOB_NUM', models.IntegerField()),
                ('PATIENT_ID_PROOF_NAME', models.CharField(max_length=45)),
                ('PATIENT_ID_PROOF_NUMBER', models.CharField(max_length=50)),
                ('PATIENT_RELATIVE_MOB_NUM', models.IntegerField()),
                ('PATIENT_EMAIL_ID', models.EmailField(max_length=60)),
                ('PATIENT_RELATIVE_EMAIL', models.EmailField(max_length=60)),
                ('PATIENT_REFER_BY', models.CharField(max_length=45)),
                ('PATIENT_INFORMATION_GIVEN_BY', models.CharField(max_length=45)),
                ('PATIENT_RELATION', models.CharField(max_length=45)),
                ('PATIENT_MED_CLAIM', models.CharField(max_length=3)),
                ('PATIENT_ROOM_PRICE', models.IntegerField()),
                ('PATIENT_PHYSICIAN_CHARGE', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PATIENT_TREATING_DR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DR_ID', models.CharField(max_length=45)),
                ('TREATING_DR_NAME', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='ROOM_TYPE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ROOM_PRICE', models.IntegerField()),
                ('ROOM_TYPE', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='PATIENT_DEPOSIT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DEPOSIT_DATE', models.DateField()),
                ('DEPOSIT_AMOUNT', models.IntegerField()),
                ('PATIENT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice_app.admit_patient')),
            ],
        ),
        migrations.CreateModel(
            name='PATIENT_DAILY_EXPENSE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EXPENSE_DATETIME', models.DateTimeField()),
                ('RADIOLOGY_EXPENSE', models.IntegerField()),
                ('PATHOLOGY_EXPENSE', models.IntegerField()),
                ('PHARMACY_EXPENSE', models.IntegerField()),
                ('HOSPITAL_EXPANSES', models.IntegerField()),
                ('OTHER_EXPENSE', models.IntegerField()),
                ('REMARKS', models.CharField(max_length=45)),
                ('PATIENT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice_app.admit_patient')),
            ],
        ),
        migrations.CreateModel(
            name='PATIENT_BILL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PATIENT_BILL_NO', models.CharField(max_length=45)),
                ('PATIENT_DISCOUNT', models.IntegerField()),
                ('PAN_NO', models.CharField(max_length=45)),
                ('CIN_NO', models.CharField(max_length=45)),
                ('PATIENT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice_app.admit_patient')),
            ],
        ),
        migrations.AddField(
            model_name='admit_patient',
            name='PATIENT_ROOM_TYPE',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice_app.room_type'),
        ),
        migrations.AddField(
            model_name='admit_patient',
            name='PATIENT_TREATING_DR',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice_app.patient_treating_dr'),
        ),
    ]
