# Generated by Django 3.1.2 on 2020-11-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admit_patient',
            name='PATIENT_MOB_NUM',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='admit_patient',
            name='PATIENT_RELATIVE_MOB_NUM',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='admit_patient',
            name='PATIENT_STREET1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='admit_patient',
            name='PATIENT_STREET2',
            field=models.CharField(max_length=200),
        ),
    ]
