# Generated by Django 3.1.2 on 2020-11-04 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admit_patient',
            name='PATIENT_ROOM_PRICE',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
